# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablewidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt
from Saison import Saison
from Journee import Journee
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(100, 250, 1400, 500))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(600, 400, 1000, 500))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        # self.label = QtWidgets.QLabel(self.formLayoutWidget)
        # self.label.setObjectName("label")
        # self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        # self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        # self.label_2.setObjectName("label_2")
        # self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.label.setText(_translate("MainWindow", "Name"))
        # self.label_2.setText(_translate("MainWindow", "Price"))

if __name__=="__main__":
    class window(QtWidgets.QMainWindow):
        def __init__(self):
            super(window, self).__init__()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self)

            self.load_data()
            self.ui.tableWidget.doubleClicked.connect(self.doubleClick)

        def doubleClick(self):
            for item in self.ui.tableWidget.selectedItems():
                print(item.row(), item.column(), item.text())

        def load_data(self):
            saison = Saison()
            classement_jour1 = saison.classement_journee()

            self.ui.tableWidget.setRowCount(len(classement_jour1))
            self.ui.tableWidget.setColumnCount(7)

            self.ui.tableWidget.setHorizontalHeaderLabels(("Points dom", 'Buteurs dom', "Clubs à domicile", 'Buts dom', 'Buts exté',
                                                           "Clubs à l'extérieur", 'Buteurs exté',  'Points exté'))

            for i in range(8):
                self.ui.tableWidget.setColumnWidth(i, 175)

            row_index = 0
            for colonnes in classement_jour1:
                self.ui.tableWidget.setItem(row_index, 0, Qt.QTableWidgetItem(str(classement_jour1['Points dom'][row_index])))
                self.ui.tableWidget.setItem(row_index, 1, Qt.QTableWidgetItem(str(classement_jour1['Buteurs dom'][row_index])))
                self.ui.tableWidget.setItem(row_index, 2, Qt.QTableWidgetItem(str(classement_jour1['Clubs à domicile'][row_index])))
                self.ui.tableWidget.setItem(row_index, 3, Qt.QTableWidgetItem(str(classement_jour1['Buts dom'][row_index])))
                self.ui.tableWidget.setItem(row_index, 4, Qt.QTableWidgetItem(str(classement_jour1['Buts exté'][row_index])))
                self.ui.tableWidget.setItem(row_index, 5, Qt.QTableWidgetItem(str(classement_jour1["Clubs à l'extérieur"][row_index])))
                self.ui.tableWidget.setItem(row_index, 6, Qt.QTableWidgetItem(str(classement_jour1['Buteurs exté'][row_index])))
                self.ui.tableWidget.setItem(row_index, 7, Qt.QTableWidgetItem(str(classement_jour1['Points exté'][row_index])))
                row_index += 1


    def create_app():
        app = QtWidgets.QApplication(sys.argv)
        win = window()
        win.show()
        sys.exit(app.exec_())


    create_app()